### ISSUE TITLE
Needs a few tweaks

### ISSUE THREAD

**Issue by ghost** [germanfr/watermark-cinnamon#4]
```
 * Cinnamon version: 4.2.2
 * Distribution:     Mint 19.2 beta
 * Attach log:       none
 ```

**Issue**
Apparently incompatible with Cinnamon 4.2.2 when loaded from Extensions panel.
However, downloading the code and installing manually worked up to the point it flagged **python3-polib** as missing.
After installing the missing module (I used Synaptic), a reinstall of the extension succeeded and is now working correctly.

**Steps to reproduce**
Fresh **Linux Mint 19.2 beta** installation.
Open **Start Menu > Preferences > Extensions > Download** (tab) => Click the down arrow corresponding to Watermark, to download it.
Switch to the **Manage** tab, select **Watermark** and click the **plus sign** at the bottom to install it.
A popup will show saying it is incompatible with current Cinnamon version.

**Other information**
While manually installing Watermark without the python3-polib module installed in the system, there is a typo in the hint for its installation: sy**a**tems => sy**s**tems .

**Comment by germanfr** [comment]
Yes, I just needed to indicate the latest version number in the manifest. This is already fixed, but cinnamon maintainers haven't yet merged it.

Anyways, if you install it from settings and then install it manually (without uninstalling), it will automatically update when a new update is available. The reason it asks you for `python3-polib` is because translations need to be manually installed if you install it this way.

**Comment by ghost** [comment]
Ah, then everything's gonna be fine soon. Great, thank you for the
headsup. ☺
