### ISSUE TITLE
How to install system wide ?

### ISSUE THREAD

**Issue by julpec** [germanfr/watermark-cinnamon#5]
Hello

It's not an issue. I just wanted to know how it's possible to install this extension for all users ?
Il looked in /usr/share/cinnamon, but there is not a directory called "extensions"
Furthermore, if it's possible, how to make a default configuration for all users ?

Thanks !

 * Cinnamon version: 3.8.8
 * Distribution:    Debian 10

**Comment by germanfr** [comment]
You can install the extension system-wide by placing it into `/usr/share/cinnamon/extensions/`, though currently you will not be able to enable/disable it manually due to a bug in the interface I just discovered. To enable it by default you have to add it to the dconf array at `org.cinnamon.enabled-extensions`. 

Apart of that, the only way I know to define a default set of settings is by modifying the `settings-schema.json` file of the extension. You have to be careful because that file will be overridden whenever the extension is updated.

**Comment by julpec** [comment]
Hello

Good for me if the user can't disable it.

Yes, I saw the dconf array. I tried but nothing appear. There is no extension installed :(

Thanks for the tip about settings. I will be careful when updating the extension.

But first, I need to make it functionnal. Please, can you tell me what directory do I need to put in `/usr/share/cinnamon/extensions/` ? ([the parent one](https://github.com/germanfr/watermark-cinnamon/tree/master/watermark%40germanfr) or only [the last version directory](https://github.com/germanfr/watermark-cinnamon/tree/master/watermark%40germanfr/3.8) ?)

BTW, thanks for this extension, really nice !

Julien

**Comment by germanfr** [comment]
You have to put the folder called `watermark@germanfr` ([this one](https://github.com/germanfr/watermark-cinnamon/tree/master/watermark%40germanfr)) inside `/usr/share/cinnamon/extensions/`. It is the one which has the `metadata.json` file directly inside it, and it has to be called `watermark@germanfr` (otherwise it won't work).

Once it is there, go to dconf and edit the array.
dconf arrays look like this: `['watermark@germanfr','another@extension']`
Do not put spaces between items.

When you have edited your `settings-schema.json` defaults, execute `xlet-settings extension watermark@germanfr` and click "reset to defaults" in the upper right corner to test your defaults.

**Comment by germanfr** [comment]
I am closing this. If you have more questions you can still comment below :)

**Comment by julpec** [comment]
Yes I have ! ;)
I've tried all this but it doesn't work as I would like.
My goal is to enable the extension by default with a fixed configuration. I am in a schoI've tried all this but it doesn't work as I would like.
My goal is to enable the extension by default with a fixed configuration. I am in a high school and I would like each new user having this extension active and configured as I wish.
Currently, the extension is well installed but I can't change the default configuration. I'll run some more tests and come back later to see if I've made any progress.
I can also add dconf rules to my logon script but I didn't find the right dconf rule to make the extension active by default.
Regards

**Comment by germanfr** [comment]
The dconf key is `org.cinnamon.enabled-extensions`. You have to add the UUID (watermark@germanfr) into the array there. To change the default settings you have to edit the `settings-schema.json` file. Each setting has a "default" key where you can specify the default value. Note that this configuration is just a default, but it can be changed by the user.

**Comment by julpec** [comment]
Yes, that's it, but… it doesn't work :(
I will do more tests next days.
Thanks
Edit : no, sorry. This is working well but the extension does not get my default configuration I want.

**Comment by germanfr** [comment]
If you want to restore the deefaults at startup you can simply delete the user configuration folder at `~/.cinnamon/configs/watermark@germanfr/`.

**Comment by germanfr** [comment]
To load the default configuration after modifying it you have to reset it. When you have edited your `settings-schema.json` defaults, execute `xlet-settings extension watermark@germanfr` and click "reset to defaults" in the upper right corner to test your defaults.

**Comment by julpec** [comment]
Yes, but on first login, the home directory does not exist and the logon script have to push the default configuration in the user directory.

**Comment by julpec** [comment]
> To load the default configuration after modifying it you have to reset it. When you have edited your `settings-schema.json` defaults, execute `xlet-settings extension watermark@germanfr` and click "reset to defaults" in the upper right corner to test your defaults.

Yes, I will try all of this and I come back here this days (or this night) to give news. Thanks

**Comment by germanfr** [comment]
> Yes, but on first login, the home directory does not exist and the logon script have to push the default configuration in the user directory.

You don't have to push any default configuration to the home directory. If you edit the file in the source of the extension (under `/usr/share/cinnamon/extensions/`) and it finds no configuration file in the user directory it just loads using the defaults.

**Comment by julpec** [comment]
I have changed the defaults settings in `/usr/share/cinnamon/extensions/` and they are well applied.
However, I wanted to put a personal icon but the value "other" is not taken into account and it returns to the value "debian". 
Is it possible to set a personal icon by default?
Thanks

**Comment by germanfr** [comment]
Yes, definitely. You have to keep that as "other" and add the path to the image to the `default` key of the `custom-icon` option.

**Comment by julpec** [comment]
Ok, I have found regarding to the extension code.
In settings-schema.json, need to put first-launch default value to false. 
And now, I have all that I wanted (with a imagemagick command to generate text to a custom icon)
Thanks !
